//! SSH config routing: write `~/.unterm/ssh/config.unterm`.
//!
//! Each profile's `[ssh]` table is a map from host pattern to private
//! key path. We emit one `Match host <h> exec "test ..."` block per
//! entry, gated on the `UNTERM_PROFILE` env var so the right key only
//! gets offered when the user is actually inside the matching window.
//!
//! Worked example. Given:
//!
//! ```toml
//! # work-acme.toml
//! [ssh]
//! "github.com" = "~/.ssh/keys/work_acme_ed25519"
//! ```
//!
//! …we generate:
//!
//! ```text
//! Match host github.com exec "test \"$UNTERM_PROFILE\" = \"work-acme\""
//!     IdentityFile /Users/alice/.ssh/keys/work_acme_ed25519
//!     IdentitiesOnly yes
//! ```
//!
//! Inside a pane spawned by an Unterm window bound to `work-acme`,
//! `UNTERM_PROFILE=work-acme` lives in env, the `exec` test passes,
//! and `ssh` is restricted to that one key (`IdentitiesOnly yes`).
//! In any other context the Match misses and `ssh` falls through to
//! the user's normal config — Unterm's routing is *additive*, never
//! destructive.
//!
//! The user has to add one line to `~/.ssh/config` for these blocks
//! to be picked up:
//!
//! ```text
//! Include ~/.unterm/ssh/config.unterm
//! ```
//!
//! …surfaced via the onboarding wizard with a "one-click add" option
//! (see task #30). Until that lands, SSH routing is opt-in via manual
//! Include.

use anyhow::{Context, Result};
use std::path::PathBuf;

use crate::ProfileRegistry;

/// Path of the auto-generated SSH config fragment.
pub fn ssh_config_unterm_path() -> PathBuf {
    crate::unterm_dir().join("ssh").join("config.unterm")
}

/// Path of the user's main `~/.ssh/config`. Surfaced so the wizard
/// can offer to append the `Include` line on first run.
pub fn user_ssh_config_path() -> Option<PathBuf> {
    dirs_next::home_dir().map(|h| h.join(".ssh").join("config"))
}

/// Render the full `config.unterm` body for a registry. Pure function
/// (no I/O); the side-effecting wrapper [`write_for_registry`] calls
/// this then atomic-writes the result.
///
/// Profiles are emitted in `index.order` order so a user inspecting
/// the file sees their profiles in the same order they appear in the
/// chip dropdown. Profiles with an empty `[ssh]` table are skipped
/// entirely — the alternative (emitting a comment header but no
/// blocks) just clutters the file.
pub fn render_for_registry(registry: &ProfileRegistry) -> String {
    let mut out = String::new();
    out.push_str(
        "# Auto-generated by Unterm. Do NOT edit by hand — this file is\n\
         # rewritten on every profile change. To opt in, add to ~/.ssh/config:\n\
         #\n\
         #     Include ~/.unterm/ssh/config.unterm\n\
         #\n\n",
    );

    let mut any = false;
    for (id, profile) in registry.iter_ordered() {
        if profile.ssh.is_empty() {
            continue;
        }
        any = true;
        out.push_str(&format!("# Profile: {}\n", profile.display_name));
        for (host, key_path) in &profile.ssh {
            let expanded = expand_tilde(key_path);
            // Escape the id for inclusion in a shell double-quoted
            // string. IDs come from slugify so they can't contain `"`
            // or `\`, but defense in depth: anything weird we don't
            // expect, we strip rather than emit.
            let safe_id = sanitize_for_shell(id);
            out.push_str(&format!(
                "Match host {host} exec \"test \\\"$UNTERM_PROFILE\\\" = \\\"{safe_id}\\\"\"\n\
                 \tIdentityFile {expanded}\n\
                 \tIdentitiesOnly yes\n\n"
            ));
        }
    }

    if !any {
        out.push_str("# No profile has [ssh] entries yet.\n");
    }
    out
}

/// Render + write atomically. Creates `~/.unterm/ssh/` if missing.
/// Idempotent: writing identical content is a no-op (we still
/// re-rename, but the bytes don't change so file ctime stays put).
pub fn write_for_registry(registry: &ProfileRegistry) -> Result<()> {
    let path = ssh_config_unterm_path();
    let body = render_for_registry(registry);

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("create dir {}", parent.display()))?;
    }
    let tmp = path.with_extension("unterm.tmp");
    std::fs::write(&tmp, &body)
        .with_context(|| format!("write temp file {}", tmp.display()))?;
    std::fs::rename(&tmp, &path)
        .with_context(|| format!("rename into {}", path.display()))?;
    Ok(())
}

/// Check whether the user has wired the include line into their main
/// `~/.ssh/config`. Best-effort: any read failure (file missing,
/// permission denied) returns `false`, which keeps the wizard
/// pointing to "needs setup" rather than silently claiming everything
/// works.
pub fn user_config_has_include() -> bool {
    let Some(path) = user_ssh_config_path() else {
        return false;
    };
    let Ok(text) = std::fs::read_to_string(&path) else {
        return false;
    };
    text.lines()
        .map(str::trim_start)
        .filter(|l| !l.starts_with('#'))
        .any(|l| l.starts_with("Include") && l.contains("config.unterm"))
}

fn expand_tilde(p: &str) -> String {
    if let Some(rest) = p.strip_prefix("~/") {
        if let Some(home) = dirs_next::home_dir() {
            return home.join(rest).display().to_string();
        }
    }
    p.to_string()
}

fn sanitize_for_shell(id: &str) -> String {
    id.chars()
        .filter(|c| !matches!(c, '"' | '\\' | '$' | '`' | '\n' | '\r'))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ProfileFile;

    fn registry_with_profiles() -> ProfileRegistry {
        let mut r = ProfileRegistry::empty_for_tests();
        let mut work = ProfileFile {
            display_name: "Work — Acme".to_string(),
            ..Default::default()
        };
        work.ssh.insert(
            "github.com".to_string(),
            "~/.ssh/keys/work_acme_ed25519".to_string(),
        );
        work.ssh.insert(
            "gitlab.acme.example".to_string(),
            "~/.ssh/keys/work_acme_ed25519".to_string(),
        );
        r.insert_for_tests("work-acme".to_string(), work);

        // Profile with no ssh entries — should be skipped entirely.
        r.insert_for_tests(
            "personal".to_string(),
            ProfileFile {
                display_name: "Personal".to_string(),
                ..Default::default()
            },
        );

        r.set_order_for_tests(vec!["personal".to_string(), "work-acme".to_string()]);
        r
    }

    #[test]
    fn render_skips_profiles_without_ssh() {
        let r = registry_with_profiles();
        let out = render_for_registry(&r);
        assert!(out.contains("# Profile: Work — Acme"));
        // The personal profile has no ssh entries, so it must NOT appear.
        assert!(!out.contains("# Profile: Personal"));
    }

    #[test]
    fn render_emits_match_block_with_quoted_test() {
        let r = registry_with_profiles();
        let out = render_for_registry(&r);
        assert!(out.contains(
            "Match host github.com exec \"test \\\"$UNTERM_PROFILE\\\" = \\\"work-acme\\\"\""
        ));
        assert!(out.contains("\tIdentitiesOnly yes"));
    }

    #[test]
    fn render_expands_tilde_in_key_paths() {
        let r = registry_with_profiles();
        let out = render_for_registry(&r);
        let home = dirs_next::home_dir().unwrap();
        let expected = home.join(".ssh/keys/work_acme_ed25519");
        assert!(
            out.contains(&format!("IdentityFile {}", expected.display())),
            "expected expanded path in:\n{out}"
        );
    }

    #[test]
    fn render_header_explains_include_setup() {
        let r = ProfileRegistry::empty_for_tests();
        let out = render_for_registry(&r);
        assert!(out.contains("Include ~/.unterm/ssh/config.unterm"));
        assert!(out.contains("No profile has [ssh] entries yet."));
    }

    #[test]
    fn sanitize_strips_shell_metacharacters() {
        // slugify won't produce these in practice, but defense-in-depth:
        // if someone hand-edits a TOML to give a profile a `$bad` id,
        // we don't want the SSH config to suddenly execute it.
        assert_eq!(sanitize_for_shell("work-acme"), "work-acme");
        assert_eq!(sanitize_for_shell("work\"$evil`"), "workevil");
        assert_eq!(sanitize_for_shell("工作"), "工作"); // CJK passes through
    }

    #[test]
    fn user_config_has_include_returns_false_when_missing() {
        // We can't reliably test the positive case without mutating
        // the real ~/.ssh/config, so this just covers the safe-default
        // path (file doesn't exist, or doesn't contain the include).
        // The positive case is exercised manually by the onboarding
        // wizard tests in v0.13.
        let path = user_ssh_config_path();
        assert!(path.is_some());
    }
}
