[package]
name = "unterm-core"
version.workspace = true
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
chrono = { workspace = true, features = ["clock"] }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
dirs-next.workspace = true
portable-pty.workspace = true
unterm-protocol.workspace = true
unterm-engine.workspace = true
unterm-mcp.workspace = true
unterm-services.workspace = true
log.workspace = true

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(windows)'.build-dependencies]
embed-resource = { workspace = true }
