[package]
name = "wezterm-render-escapes"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
config.workspace = true
finl_unicode.workspace = true
lazy_static.workspace = true
terminfo.workspace = true
termwiz = { workspace=true, features=["use_serde"] }
wezterm-dynamic.workspace = true
